const commerceFallback = [
  ['aud-01','Auriculares NOVA Pulse','audio',249000,319000,true,'Auriculares inalámbricos con cancelación de ruido activa y 30h de batería.'],['aud-02','Parlante KREW Boom','audio',189000,0,false,'Parlante portátil resistente al agua IPX6, sonido 360°.'],['cal-01','Tenis GRYT Runner','calzado',329000,0,false,'Suela de espuma reactiva, malla transpirable, edición urbana.'],['cal-02','Botas URBN Trek','calzado',279000,349000,true,'Botas impermeables con suela antideslizante para ciudad.'],['ropa-01','Chaqueta KREW Shell','apparel',219000,0,false,'Cortavientos técnico con bolsillos sellados y capucha ajustable.'],['ropa-02','Hoodie NOVA Grid','apparel',139000,0,false,'Hoodie de algodón pesado con estampado reflectivo.'],['gad-01','Power Bank VOLT 20K','gadgets',129000,159000,true,'20.000 mAh, carga rápida 65W, doble puerto USB-C.'],['gad-02','Cable TRAX USB-C 2m','gadgets',39000,0,false,'Cable trenzado reforzado, carga rápida 100W.'],['gad-03','Smartwatch PULSE X','gadgets',349000,0,false,'Monitor de ritmo cardíaco, GPS y batería de 7 días.'],['hog-01','Lámpara LOOP LED','hogar',89000,0,false,'Lámpara de escritorio regulable con carga inalámbrica en la base.'],['game-01','Control ARC Wireless','gaming',169000,199000,true,'Control inalámbrico multiplataforma con gatillos programables.'],['game-02','Soporte GRID Console','gaming',59000,0,false,'Soporte vertical con ventilación para consolas de nueva generación.']
].map(item => ({id:item[0],nombre:item[1],categoria:item[2],precio:item[3],precioAnterior:item[4],oferta:item[5],descripcion:item[6],icono:item[2],stock:12}));
const commerceLabels={audio:'Audio',calzado:'Calzado',apparel:'Apparel',gadgets:'Gadgets',hogar:'Hogar',gaming:'Gaming'};
const commerceColors={audio:'#1976d2',calzado:'#3d6f9f',apparel:'#315d80',gadgets:'#147f9c',hogar:'#597590',gaming:'#2453a0'};
let commerceProducts=[];let commerceCategory='todos';let commerceSearch='';let commerceView='all';let commerceCart=JSON.parse(localStorage.getItem('krew-cart-items')||'[]');let commerceFavorites=new Set(JSON.parse(localStorage.getItem('krew-favorites')||'[]'));
const productGrid=document.querySelector('#mobile-products');const cartDialog=document.querySelector('#cart-dialog');const checkoutDialog=document.querySelector('#checkout-dialog');
const price=value=>value.toLocaleString('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0});
const toastMessage=message=>{const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastMessage.timer);toastMessage.timer=setTimeout(()=>toast.classList.remove('show'),1800)};
function cartCount(){return commerceCart.reduce((sum,item)=>sum+item.quantity,0)}function saveFavorites(){localStorage.setItem('krew-favorites',JSON.stringify([...commerceFavorites]))}function saveCart(){localStorage.setItem('krew-cart-items',JSON.stringify(commerceCart));document.querySelectorAll('#cart-count,#cart-count-bottom').forEach(item=>item.textContent=cartCount())}
function filteredProducts(){return commerceProducts.filter(item=>(commerceCategory==='todos'||item.categoria===commerceCategory)&&(!commerceSearch||`${item.nombre} ${item.descripcion}`.toLowerCase().includes(commerceSearch.toLowerCase()))&&(commerceView!=='favorites'||commerceFavorites.has(item.id)))}
function renderProducts(){const items=filteredProducts();document.querySelector('#product-count').textContent=`${items.length} ${items.length===1?'producto':'productos'}`;productGrid.innerHTML=items.length?items.map(item=>`<article class="mobile-product" data-id="${item.id}" style="--accent:${commerceColors[item.categoria]}"><div class="product-visual">${item.oferta?'<span class="tag">OFERTA</span>':''}<button class="favorite ${commerceFavorites.has(item.id)?'active':''}" data-favorite="${item.id}" aria-label="Favorito">${commerceFavorites.has(item.id)?'♥':'♡'}</button>${getIcon(item.icono)}</div><div class="mobile-product-body"><span class="product-category">${commerceLabels[item.categoria]}</span><h3>${item.nombre}</h3><span class="mobile-price">${price(item.precio)}</span>${item.oferta?`<span class="mobile-old-price">${price(item.precioAnterior)}</span>`:''}<button class="add-product" data-add="${item.id}" aria-label="Agregar al carrito">+</button></div></article>`).join(''):'<div class="loading-state">No encontramos productos con esa selección.</div>';productGrid.querySelectorAll('[data-add]').forEach(button=>button.onclick=event=>{event.stopPropagation();addToCart(button.dataset.add)});productGrid.querySelectorAll('[data-favorite]').forEach(button=>button.onclick=event=>{event.stopPropagation();toggleFavorite(button.dataset.favorite)});productGrid.querySelectorAll('.mobile-product').forEach(card=>card.onclick=()=>openProduct(card.dataset.id))}
function toggleFavorite(id){commerceFavorites.has(id)?commerceFavorites.delete(id):commerceFavorites.add(id);saveFavorites();renderProducts();toastMessage(commerceFavorites.has(id)?'Guardado en favoritos':'Quitado de favoritos')}
function addToCart(id){const item=commerceCart.find(entry=>entry.id===id);if(item)item.quantity+=1;else commerceCart.push({id,quantity:1});saveCart();toastMessage('Producto agregado al carrito')}
function openProduct(id){const item=commerceProducts.find(product=>product.id===id);if(!item)return;document.querySelector('#dialog-content').innerHTML=`<div class="dialog-visual" style="background:${commerceColors[item.categoria]}16;color:${commerceColors[item.categoria]}">${getIcon(item.icono)}</div><span class="dialog-inner-category">${commerceLabels[item.categoria]}</span><h2>${item.nombre}</h2><p>${item.descripcion}</p><span class="dialog-price">${price(item.precio)}</span><button class="dialog-add" id="dialog-add">Agregar al carrito</button>`;document.querySelector('#product-dialog').showModal();document.querySelector('#dialog-add').onclick=()=>{addToCart(item.id);document.querySelector('#product-dialog').close()}}
function renderCart(){const list=document.querySelector('#cart-list');const entries=commerceCart.map(entry=>({...entry,product:commerceProducts.find(item=>item.id===entry.id)})).filter(entry=>entry.product);const total=entries.reduce((sum,entry)=>sum+entry.product.precio*entry.quantity,0);list.innerHTML=entries.length?entries.map(entry=>`<div class="cart-item"><div class="cart-item-visual" style="background:${commerceColors[entry.product.categoria]}16">${getIcon(entry.product.icono)}</div><div><strong>${entry.product.nombre}</strong><small>${entry.quantity} unidad${entry.quantity===1?'':'es'}</small></div><div class="cart-item-side"><strong>${price(entry.product.precio*entry.quantity)}</strong><button class="remove-item" data-remove="${entry.id}">Eliminar</button></div></div>`).join(''):'<div class="cart-empty">Tu carrito está vacío.<br>Agrega un producto para comenzar.</div>';document.querySelector('#cart-total').textContent=price(total);document.querySelector('#checkout-button').disabled=!entries.length;list.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{commerceCart=commerceCart.filter(entry=>entry.id!==button.dataset.remove);saveCart();renderCart()})}
function openCart(){renderCart();cartDialog.showModal()}
document.querySelectorAll('.category-chip').forEach(button=>button.onclick=()=>{document.querySelectorAll('.category-chip').forEach(item=>item.classList.remove('active'));button.classList.add('active');commerceCategory=button.dataset.category;commerceView='all';renderProducts()});document.querySelector('#mobile-search').oninput=event=>{commerceSearch=event.target.value;document.querySelector('#clear-search').style.display=commerceSearch?'block':'none';renderProducts()};document.querySelector('#clear-search').onclick=()=>{document.querySelector('#mobile-search').value='';commerceSearch='';document.querySelector('#clear-search').style.display='none';renderProducts()};document.querySelector('[data-scroll-products]').onclick=()=>document.querySelector('.store-content').scrollIntoView({behavior:'smooth'});document.querySelector('#filter-button').onclick=()=>toastMessage('Elige una categoría para filtrar');document.querySelectorAll('.cart-trigger').forEach(button=>button.onclick=event=>{event.stopPropagation();openCart()});document.querySelector('.dialog-close').onclick=()=>document.querySelector('#product-dialog').close();document.querySelector('.cart-close').onclick=()=>cartDialog.close();document.querySelector('#checkout-button').onclick=()=>{if(cartCount()){cartDialog.close();checkoutDialog.showModal()}};document.querySelector('.checkout-close').onclick=()=>checkoutDialog.close();document.querySelector('#checkout-form').onsubmit=event=>{event.preventDefault();commerceCart=[];saveCart();checkoutDialog.close();toastMessage('Compra simulada confirmada. ¡Gracias por comprar en KREW!');event.target.reset()};document.querySelectorAll('[data-nav]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-nav]').forEach(item=>item.classList.remove('active'));button.classList.add('active');commerceView=button.dataset.nav==='favoritos'?'favorites':'all';if(button.dataset.nav==='buscar')document.querySelector('#mobile-search').focus();renderProducts()});
fetchProducts().then(data=>{commerceProducts=data;renderProducts();saveCart()}).catch(()=>{commerceProducts=commerceFallback;renderProducts();saveCart()});
